apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    crossplane.io/external-name: scratch-code-prod
    meta.io.cvshealth.com/tenant: "scratch"
    meta.io.cvshealth.com/cost-center: "23451"
  labels:
    tenant: "scratch"
    cost-center: "23451"
  name: scratch-code-prod
spec:
  deletionPolicy: Orphan 
  forProvider:
    location: US
    labels:
      tenant: scratch
      # dataClassification: proprietary
      cost-center: "23451"
    uniformBucketLevelAccess: true
  providerConfigRef:
    name: default