apiVersion: kyverno.io/v1
kind: Policy
metadata:
  annotations:
    policies.kyverno.io/category: BucketName Validation
    policies.kyverno.io/description: Validate if the Bucket Name
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Bucket Creation Validation Check
    policies.kyverno.io/title: BucketName Validation Check
  labels:
    argocd.argoproj.io/instance: kyverno-policies
  name: bucketnamevalidation
spec:
  validationFailureAction: Enforce
  rules:
  - match:
      resources:
        kinds:
        - Bucket
    name: bucket-name-check
    validate:
      message: Please create bucket name following IO Standards
      pattern: "^io-[a-z][a-z]"
      patternType: "regexp"