apiVersion: kyverno.io/v1
kind: Policy
metadata:
  annotations:
    policies.kyverno.io/category: BucketName Validation
    policies.kyverno.io/description: Enfore Bucket Name to follow IO-Standards
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: BucketName Validation Check
    policies.kyverno.io/title: BucketName Validation Check
  labels:
    argocd.argoproj.io/instance: kyverno-policies
  name: enforce-bucket-name
spec:
  validationFailureAction: Enforce
  rules:
  - match:
      resources:
        kinds:
          - Bucket
    name: bucket-name-check
    validate:
      message: Please create bucket name following IO Standards
      pattern: 
        metadata:
          name: scratch-code-(pdev|dev|test|prod)
      patternType: "regexp"